// TODO: replace with real API call
// Seed data for the mock marketplace. Only marketplaceService.js (through MarketplaceProvider)
// reads it - pages must go through the service.
// Part numbers follow real formats, but the numbers, prices and fitment year ranges are
// illustrative only - they have not been checked against a parts catalog.

export const shops = [
  {
    id: 'alquds-auto-parts',
    name: 'Al-Quds Auto Parts',
    city: 'Nablus',
    description: 'Brakes, filters and electrical parts for European and Korean cars. Same-day pickup in Nablus.',
  },
  {
    id: 'ramallah-motors-supply',
    name: 'Ramallah Motors Supply',
    city: 'Ramallah',
    description: 'Aftermarket parts from Bosch, Brembo and Gates, plus clutch and transmission kits.',
  },
  {
    id: 'jenin-spare-parts',
    name: 'Jenin Spare Parts Center',
    city: 'Jenin',
    description: 'New and used parts, including tested used body parts and refurbished alternators.',
  },
  {
    id: 'tulkarm-car-accessories',
    name: 'Tulkarm Car Accessories',
    city: 'Tulkarm',
    description: 'Lighting, accessories and cooling parts. Headlight fitting available on request.',
  },
  {
    id: 'hebron-genuine-parts',
    name: 'Hebron Genuine Parts',
    city: 'Hebron',
    description: 'Genuine OEM parts for VW, Toyota, Hyundai, Kia and Mercedes-Benz.',
  },
]

const fit = (make, model, yearFrom, yearTo) => ({ make, model, yearFrom, yearTo })

// Shared fitments, reused by several parts below.
const VW_GROUP_PQ35 = [
  fit('Volkswagen', 'Golf', 2004, 2013),
  fit('Volkswagen', 'Jetta', 2005, 2014),
  fit('Skoda', 'Octavia', 2004, 2013),
  fit('Audi', 'A3', 2004, 2012),
]
const VW_GROUP_MQB = [
  fit('Volkswagen', 'Golf', 2013, 2020),
  fit('Skoda', 'Octavia', 2013, 2020),
  fit('Audi', 'A3', 2013, 2020),
]
const HYUNDAI_KIA_SMALL_ENGINES = [
  fit('Hyundai', 'Elantra', 2011, 2020),
  fit('Hyundai', 'Tucson', 2010, 2020),
  fit('Hyundai', 'Accent', 2011, 2022),
  fit('Kia', 'Sportage', 2011, 2021),
  fit('Kia', 'Rio', 2012, 2021),
  fit('Kia', 'Cerato', 2013, 2021),
]

export const parts = [
  // --- VW group: one brake disc from three shops, fitting Golf, Jetta, Octavia and A3 ---
  {
    id: 'p-001',
    name: 'Front brake disc, 288 mm vented',
    oemNumber: '1K0615301AA',
    manufacturerNumber: '0986479099',
    brand: 'Bosch',
    category: 'Brakes',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 185,
    stock: 12,
    shopId: 'alquds-auto-parts',
    addedAt: '2026-09-20',
    fitments: VW_GROUP_PQ35,
  },
  {
    id: 'p-002',
    name: 'Front brake disc, 288 mm vented',
    oemNumber: '1K0615301AA',
    manufacturerNumber: '1K0615301AA',
    brand: 'OEM/Genuine',
    category: 'Brakes',
    type: 'oem',
    condition: 'new',
    priceIls: 320,
    stock: 4,
    shopId: 'hebron-genuine-parts',
    addedAt: '2026-08-11',
    fitments: VW_GROUP_PQ35,
  },
  {
    id: 'p-003',
    name: 'Front brake disc, 288 mm vented',
    oemNumber: '1K0615301AA',
    manufacturerNumber: '09.9145.11',
    brand: 'Brembo',
    category: 'Brakes',
    type: 'aftermarket',
    condition: 'used',
    priceIls: 90,
    stock: 2,
    shopId: 'jenin-spare-parts',
    addedAt: '2026-09-02',
    fitments: VW_GROUP_PQ35,
  },
  {
    id: 'p-004',
    name: 'Front brake pad set',
    oemNumber: '1K0698151A',
    manufacturerNumber: 'P 85 075',
    brand: 'Brembo',
    category: 'Brakes',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 160,
    stock: 20,
    shopId: 'ramallah-motors-supply',
    addedAt: '2026-07-28',
    fitments: VW_GROUP_PQ35,
  },
  {
    id: 'p-005',
    name: 'Oil filter, 1.6/2.0 TDI',
    oemNumber: '03N115562B',
    manufacturerNumber: 'HU 6004 x',
    brand: 'Mann-Filter',
    category: 'Filters',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 38,
    stock: 40,
    shopId: 'alquds-auto-parts',
    addedAt: '2026-09-15',
    fitments: [...VW_GROUP_MQB, fit('Volkswagen', 'Passat', 2015, 2023), fit('Volkswagen', 'Tiguan', 2016, 2024)],
  },
  {
    id: 'p-006',
    name: 'Engine air filter',
    oemNumber: '5Q0129620B',
    manufacturerNumber: 'C 27 009',
    brand: 'Mann-Filter',
    category: 'Filters',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 55,
    stock: 15,
    shopId: 'tulkarm-car-accessories',
    addedAt: '2026-08-19',
    fitments: VW_GROUP_MQB,
  },
  {
    id: 'p-007',
    name: 'Poly-V serpentine belt 6PK1070',
    oemNumber: '04E260849B',
    manufacturerNumber: '6PK1070',
    brand: 'Gates',
    category: 'Engine',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 65,
    stock: 9,
    shopId: 'ramallah-motors-supply',
    addedAt: '2026-06-30',
    fitments: [fit('Volkswagen', 'Golf', 2013, 2020), fit('Volkswagen', 'Polo', 2014, 2021), fit('Skoda', 'Octavia', 2013, 2020)],
  },
  {
    id: 'p-008',
    name: 'Ignition coil, 1.2/1.4 TSI',
    oemNumber: '04E905110K',
    manufacturerNumber: '0986221095',
    brand: 'Bosch',
    category: 'Electrical',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 140,
    stock: 6,
    shopId: 'alquds-auto-parts',
    addedAt: '2026-09-08',
    fitments: [
      fit('Volkswagen', 'Golf', 2013, 2020),
      fit('Volkswagen', 'Polo', 2014, 2021),
      fit('Skoda', 'Octavia', 2013, 2020),
      fit('Skoda', 'Fabia', 2015, 2021),
    ],
  },
  {
    id: 'p-009',
    name: 'Iridium spark plug',
    oemNumber: '04E905612C',
    manufacturerNumber: 'ILKAR7L11',
    brand: 'NGK',
    category: 'Engine',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 42,
    stock: 60,
    shopId: 'jenin-spare-parts',
    addedAt: '2026-07-12',
    fitments: [
      fit('Volkswagen', 'Golf', 2013, 2020),
      fit('Volkswagen', 'Jetta', 2015, 2020),
      fit('Volkswagen', 'Polo', 2014, 2021),
      fit('Skoda', 'Octavia', 2013, 2020),
    ],
  },
  {
    id: 'p-010',
    name: 'Clutch kit, 3-piece',
    oemNumber: '0A5141031',
    manufacturerNumber: '3000 950 016',
    brand: 'Sachs',
    category: 'Transmission',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 890,
    stock: 2,
    shopId: 'ramallah-motors-supply',
    addedAt: '2026-08-03',
    fitments: [fit('Volkswagen', 'Golf', 2009, 2013), fit('Volkswagen', 'Jetta', 2011, 2014), fit('Skoda', 'Octavia', 2009, 2013)],
  },
  {
    id: 'p-011',
    name: 'Water pump with thermostat housing',
    oemNumber: '04E121600AD',
    manufacturerNumber: '506950',
    brand: 'Valeo',
    category: 'Cooling',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 310,
    stock: 3,
    shopId: 'hebron-genuine-parts',
    addedAt: '2026-09-18',
    fitments: [fit('Volkswagen', 'Golf', 2013, 2020), fit('Volkswagen', 'Polo', 2014, 2021), fit('Skoda', 'Octavia', 2013, 2020)],
  },
  {
    id: 'p-012',
    name: 'LED headlight, left',
    oemNumber: '5G1941005',
    manufacturerNumber: '046750',
    brand: 'Valeo',
    category: 'Lighting',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 1450,
    stock: 1,
    shopId: 'tulkarm-car-accessories',
    addedAt: '2026-09-24',
    fitments: [fit('Volkswagen', 'Golf', 2013, 2017)],
  },
  {
    id: 'p-013',
    name: 'Front bumper cover (unpainted)',
    oemNumber: '5G0807221',
    manufacturerNumber: '5G0807221',
    brand: 'OEM/Genuine',
    category: 'Body',
    type: 'oem',
    condition: 'used',
    priceIls: 750,
    stock: 1,
    shopId: 'jenin-spare-parts',
    addedAt: '2026-08-27',
    fitments: [fit('Volkswagen', 'Golf', 2013, 2017)],
  },
  {
    id: 'p-014',
    name: 'Rubber floor mat set, 4 pieces',
    oemNumber: '5G1061500',
    manufacturerNumber: 'FM-GOLF7',
    brand: 'Unbranded',
    category: 'Accessories',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 120,
    stock: 11,
    shopId: 'tulkarm-car-accessories',
    addedAt: '2026-06-14',
    fitments: [fit('Volkswagen', 'Golf', 2013, 2020)],
  },

  // --- Toyota ---
  {
    id: 'p-015',
    name: 'Oil filter cartridge',
    oemNumber: '04152-YZZA1',
    manufacturerNumber: 'HU 7019 z',
    brand: 'Mann-Filter',
    category: 'Filters',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 35,
    stock: 25,
    shopId: 'alquds-auto-parts',
    addedAt: '2026-07-05',
    fitments: [fit('Toyota', 'Corolla', 2007, 2019), fit('Toyota', 'RAV4', 2013, 2018), fit('Toyota', 'Camry', 2012, 2017)],
  },
  {
    id: 'p-016',
    name: 'Oil filter cartridge',
    oemNumber: '04152-YZZA1',
    manufacturerNumber: '04152-YZZA1',
    brand: 'OEM/Genuine',
    category: 'Filters',
    type: 'oem',
    condition: 'new',
    priceIls: 48,
    stock: 30,
    shopId: 'hebron-genuine-parts',
    addedAt: '2026-09-01',
    fitments: [fit('Toyota', 'Corolla', 2007, 2019), fit('Toyota', 'RAV4', 2013, 2018), fit('Toyota', 'Camry', 2012, 2017)],
  },
  {
    id: 'p-017',
    name: 'Front brake pad set',
    oemNumber: '04465-02220',
    manufacturerNumber: '0986494575',
    brand: 'Bosch',
    category: 'Brakes',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 150,
    stock: 10,
    shopId: 'ramallah-motors-supply',
    addedAt: '2026-08-22',
    fitments: [fit('Toyota', 'Corolla', 2013, 2019)],
  },
  {
    id: 'p-018',
    name: 'Ignition coil, 1.6/1.8 petrol',
    oemNumber: '90919-02252',
    manufacturerNumber: '673-1308',
    brand: 'Denso',
    category: 'Electrical',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 175,
    stock: 4,
    shopId: 'jenin-spare-parts',
    addedAt: '2026-07-19',
    fitments: [fit('Toyota', 'Corolla', 2007, 2019), fit('Toyota', 'Yaris', 2011, 2019)],
  },
  {
    id: 'p-019',
    name: 'Radiator, manual transmission',
    oemNumber: '16400-0T040',
    manufacturerNumber: 'DRM50088',
    brand: 'Denso',
    category: 'Cooling',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 620,
    stock: 2,
    shopId: 'tulkarm-car-accessories',
    addedAt: '2026-06-21',
    fitments: [fit('Toyota', 'Corolla', 2008, 2013)],
  },
  {
    id: 'p-020',
    name: 'Front shock absorber',
    oemNumber: '48510-80728',
    manufacturerNumber: '317 578',
    brand: 'Sachs',
    category: 'Suspension',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 280,
    stock: 0,
    shopId: 'alquds-auto-parts',
    addedAt: '2026-08-08',
    fitments: [fit('Toyota', 'Camry', 2012, 2017)],
  },
  {
    id: 'p-021',
    name: 'Headlight assembly, right',
    oemNumber: '81110-06640',
    manufacturerNumber: '81110-06640',
    brand: 'OEM/Genuine',
    category: 'Lighting',
    type: 'oem',
    condition: 'used',
    priceIls: 380,
    stock: 1,
    shopId: 'jenin-spare-parts',
    addedAt: '2026-09-11',
    fitments: [fit('Toyota', 'Camry', 2015, 2017)],
  },
  {
    id: 'p-022',
    name: 'Rear bumper cover',
    oemNumber: '52159-0D928',
    manufacturerNumber: 'TY-YAR-RB14',
    brand: 'Unbranded',
    category: 'Body',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 520,
    stock: 3,
    shopId: 'ramallah-motors-supply',
    addedAt: '2026-07-24',
    fitments: [fit('Toyota', 'Yaris', 2014, 2017)],
  },

  // --- Hyundai / Kia: shared parts across both brands ---
  {
    id: 'p-023',
    name: 'Oil filter',
    oemNumber: '26300-35505',
    manufacturerNumber: 'W 811/80',
    brand: 'Mann-Filter',
    category: 'Filters',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 28,
    stock: 50,
    shopId: 'ramallah-motors-supply',
    addedAt: '2026-09-05',
    fitments: HYUNDAI_KIA_SMALL_ENGINES,
  },
  {
    id: 'p-024',
    name: 'Oil filter',
    oemNumber: '26300-35505',
    manufacturerNumber: '26300-35505',
    brand: 'OEM/Genuine',
    category: 'Filters',
    type: 'oem',
    condition: 'new',
    priceIls: 40,
    stock: 35,
    shopId: 'hebron-genuine-parts',
    addedAt: '2026-08-15',
    fitments: HYUNDAI_KIA_SMALL_ENGINES,
  },
  {
    id: 'p-025',
    name: 'Rear brake pad set',
    oemNumber: '58302-2SA30',
    manufacturerNumber: 'P 30 047',
    brand: 'Brembo',
    category: 'Brakes',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 170,
    stock: 7,
    shopId: 'tulkarm-car-accessories',
    addedAt: '2026-07-30',
    fitments: [fit('Hyundai', 'Tucson', 2010, 2015), fit('Kia', 'Sportage', 2011, 2016)],
  },
  {
    id: 'p-026',
    name: 'Engine air filter',
    oemNumber: '28113-2S000',
    manufacturerNumber: 'C 26 003',
    brand: 'Mann-Filter',
    category: 'Filters',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 45,
    stock: 18,
    shopId: 'alquds-auto-parts',
    addedAt: '2026-06-26',
    fitments: [fit('Hyundai', 'Tucson', 2010, 2015), fit('Kia', 'Sportage', 2011, 2016)],
  },
  {
    id: 'p-027',
    name: 'Alternator 90A',
    oemNumber: '37300-2B100',
    manufacturerNumber: '440588',
    brand: 'Valeo',
    category: 'Electrical',
    type: 'aftermarket',
    condition: 'refurbished',
    priceIls: 650,
    stock: 2,
    shopId: 'jenin-spare-parts',
    addedAt: '2026-09-22',
    fitments: [
      fit('Hyundai', 'Elantra', 2011, 2016),
      fit('Hyundai', 'Accent', 2011, 2017),
      fit('Kia', 'Rio', 2012, 2017),
      fit('Kia', 'Cerato', 2013, 2018),
    ],
  },
  {
    id: 'p-028',
    name: 'Wiper blade set, front',
    oemNumber: '98350-3X000',
    manufacturerNumber: '3397007297',
    brand: 'Bosch',
    category: 'Accessories',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 75,
    stock: 22,
    shopId: 'tulkarm-car-accessories',
    addedAt: '2026-08-29',
    fitments: [fit('Hyundai', 'Elantra', 2011, 2016), fit('Kia', 'Cerato', 2013, 2018)],
  },
  {
    id: 'p-029',
    name: 'Front brake disc pair',
    oemNumber: '51712-07000',
    manufacturerNumber: '09.A868.10',
    brand: 'Brembo',
    category: 'Brakes',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 210,
    stock: 5,
    shopId: 'ramallah-motors-supply',
    addedAt: '2026-07-08',
    fitments: [fit('Kia', 'Picanto', 2011, 2017), fit('Hyundai', 'i10', 2008, 2013)],
  },

  // --- Mercedes-Benz ---
  {
    id: 'p-030',
    name: 'Oil filter, M271 engine',
    oemNumber: 'A2711800009',
    manufacturerNumber: 'HU 514 x',
    brand: 'Mann-Filter',
    category: 'Filters',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 60,
    stock: 12,
    shopId: 'hebron-genuine-parts',
    addedAt: '2026-09-13',
    fitments: [fit('Mercedes-Benz', 'C-Class', 2007, 2014), fit('Mercedes-Benz', 'E-Class', 2009, 2016)],
  },
  {
    id: 'p-031',
    name: 'Front brake pad set',
    oemNumber: 'A0074208520',
    manufacturerNumber: '0986494712',
    brand: 'Bosch',
    category: 'Brakes',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 290,
    stock: 6,
    shopId: 'alquds-auto-parts',
    addedAt: '2026-08-01',
    fitments: [fit('Mercedes-Benz', 'C-Class', 2014, 2021), fit('Mercedes-Benz', 'E-Class', 2016, 2023)],
  },
  {
    id: 'p-032',
    name: 'Xenon bulb D1S',
    oemNumber: 'A0028202977',
    manufacturerNumber: '8GS 009 144-001',
    brand: 'Hella',
    category: 'Lighting',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 240,
    stock: 8,
    shopId: 'tulkarm-car-accessories',
    addedAt: '2026-09-26',
    fitments: [fit('Mercedes-Benz', 'C-Class', 2007, 2014), fit('Mercedes-Benz', 'E-Class', 2009, 2016)],
  },
  {
    id: 'p-033',
    name: 'Transmission mount',
    oemNumber: 'A2042400418',
    manufacturerNumber: 'A2042400418',
    brand: 'OEM/Genuine',
    category: 'Transmission',
    type: 'oem',
    condition: 'used',
    priceIls: 180,
    stock: 1,
    shopId: 'jenin-spare-parts',
    addedAt: '2026-07-16',
    fitments: [fit('Mercedes-Benz', 'C-Class', 2007, 2014)],
  },

  // --- Steering: the same part name for different cars ---
  {
    id: 'p-034',
    name: 'Steering wheel, leather',
    oemNumber: '56110-1R000',
    manufacturerNumber: '56110-1R000',
    brand: 'OEM/Genuine',
    category: 'Steering',
    type: 'oem',
    condition: 'used',
    priceIls: 450,
    stock: 1,
    shopId: 'jenin-spare-parts',
    addedAt: '2026-09-27',
    fitments: [fit('Hyundai', 'Accent', 2011, 2017)],
  },
  {
    id: 'p-035',
    name: 'Steering wheel, leather',
    oemNumber: '45100-02D10',
    manufacturerNumber: '45100 02D10',
    brand: 'OEM/Genuine',
    category: 'Steering',
    type: 'oem',
    condition: 'new',
    priceIls: 980,
    stock: 2,
    shopId: 'hebron-genuine-parts',
    addedAt: '2026-09-10',
    fitments: [fit('Toyota', 'Corolla', 2013, 2018)],
  },
  {
    id: 'p-036',
    name: 'Steering wheel, multifunction',
    oemNumber: '56100-1W000',
    manufacturerNumber: 'SW-KR 1W000',
    brand: 'Unbranded',
    category: 'Steering',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 620,
    stock: 3,
    shopId: 'tulkarm-car-accessories',
    addedAt: '2026-09-19',
    fitments: [fit('Kia', 'Rio', 2012, 2016)],
  },
  {
    id: 'p-037',
    name: 'Steering wheel cover, 38 cm',
    oemNumber: 'UNI-SWC-38',
    manufacturerNumber: 'SWC.38.BLK',
    brand: 'Unbranded',
    category: 'Accessories',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 45,
    stock: 30,
    shopId: 'tulkarm-car-accessories',
    addedAt: '2026-08-25',
    fitments: [
      fit('Hyundai', 'Accent', 2011, 2022),
      fit('Hyundai', 'Elantra', 2011, 2020),
      fit('Kia', 'Rio', 2012, 2021),
      fit('Toyota', 'Corolla', 2007, 2019),
      fit('Toyota', 'Yaris', 2011, 2019),
    ],
  },
  {
    id: 'p-038',
    name: 'Tie rod end, outer',
    oemNumber: '56820-1R000',
    manufacturerNumber: 'JTE 1034',
    brand: 'TRW',
    category: 'Steering',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 95,
    stock: 14,
    shopId: 'ramallah-motors-supply',
    addedAt: '2026-08-17',
    fitments: [fit('Hyundai', 'Accent', 2011, 2017), fit('Kia', 'Rio', 2012, 2017)],
  },
  {
    id: 'p-039',
    name: 'Power steering pump',
    oemNumber: '44310-02250',
    manufacturerNumber: 'DSP 1302',
    brand: 'Denso',
    category: 'Steering',
    type: 'aftermarket',
    condition: 'refurbished',
    priceIls: 540,
    stock: 2,
    shopId: 'jenin-spare-parts',
    addedAt: '2026-07-21',
    fitments: [fit('Toyota', 'Corolla', 2007, 2013)],
  },

  // --- More Hyundai / Kia / Toyota ---
  {
    id: 'p-040',
    name: 'Front brake pad set',
    oemNumber: '58101-1RA00',
    manufacturerNumber: '0 986 494 562',
    brand: 'Bosch',
    category: 'Brakes',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 145,
    stock: 16,
    shopId: 'alquds-auto-parts',
    addedAt: '2026-09-23',
    fitments: [fit('Hyundai', 'Accent', 2011, 2017), fit('Kia', 'Rio', 2012, 2017)],
  },
  {
    id: 'p-041',
    name: 'Headlight assembly, left',
    oemNumber: '92101-1R000',
    manufacturerNumber: 'HY-ACC HL.L',
    brand: 'Depo',
    category: 'Lighting',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 410,
    stock: 4,
    shopId: 'tulkarm-car-accessories',
    addedAt: '2026-09-14',
    fitments: [fit('Hyundai', 'Accent', 2011, 2014)],
  },
  {
    id: 'p-042',
    name: 'Cabin air filter',
    oemNumber: '97133-2E210',
    manufacturerNumber: 'CU 2533',
    brand: 'Mann-Filter',
    category: 'Filters',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 40,
    stock: 28,
    shopId: 'ramallah-motors-supply',
    addedAt: '2026-09-06',
    fitments: [
      fit('Hyundai', 'Accent', 2011, 2017),
      fit('Hyundai', 'Elantra', 2011, 2016),
      fit('Hyundai', 'Tucson', 2015, 2020),
      fit('Kia', 'Rio', 2012, 2017),
      fit('Kia', 'Sportage', 2016, 2021),
    ],
  },
  {
    id: 'p-043',
    name: 'Spark plug, nickel',
    oemNumber: '90919-01253',
    manufacturerNumber: 'K16R-U11',
    brand: 'Denso',
    category: 'Engine',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 22,
    stock: 80,
    shopId: 'hebron-genuine-parts',
    addedAt: '2026-08-05',
    fitments: [fit('Toyota', 'Corolla', 2007, 2019), fit('Toyota', 'Yaris', 2006, 2019)],
  },

  // --- Tires & Wheels ---
  {
    id: 'p-044',
    name: 'Alloy wheel 15", 5-spoke silver',
    oemNumber: '52910-1R250',
    manufacturerNumber: 'RW-1545-S',
    brand: 'Ronal',
    category: 'Tires & Wheels',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 520,
    stock: 8,
    shopId: 'tulkarm-car-accessories',
    addedAt: '2026-09-22',
    fitments: [fit('Hyundai', 'Accent', 2011, 2017), fit('Kia', 'Rio', 2012, 2017)],
  },
  {
    id: 'p-045',
    name: 'Summer tire 195/55 R15',
    oemNumber: '52933-1R100',
    manufacturerNumber: 'MIC-PS4-1955515',
    brand: 'Michelin',
    category: 'Tires & Wheels',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 340,
    stock: 24,
    shopId: 'jenin-spare-parts',
    addedAt: '2026-09-18',
    fitments: [
      fit('Hyundai', 'Accent', 2011, 2017),
      fit('Kia', 'Rio', 2012, 2017),
      fit('Toyota', 'Yaris', 2011, 2019),
    ],
  },
  {
    id: 'p-046',
    name: 'Alloy wheel 16", twin-spoke black',
    oemNumber: '5G0601025',
    manufacturerNumber: 'AEZ-1665-B',
    brand: 'AEZ',
    category: 'Tires & Wheels',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 690,
    stock: 4,
    shopId: 'tulkarm-car-accessories',
    addedAt: '2026-09-24',
    fitments: VW_GROUP_MQB,
  },

  // --- Oils & fluids, tools and more accessories. universalFit: fits every car (no fitments) ---
  {
    id: 'p-047',
    name: 'Engine oil 5W-30 fully synthetic, 4 L',
    oemNumber: '',
    manufacturerNumber: '15F7EA',
    brand: 'Castrol',
    category: 'Oils & Fluids',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 145,
    stock: 40,
    shopId: 'ramallah-motors-supply',
    addedAt: '2026-09-22',
    fitments: [],
    universalFit: true,
  },
  {
    id: 'p-048',
    name: 'Engine oil 10W-40 semi-synthetic, 4 L',
    oemNumber: '',
    manufacturerNumber: '214106',
    brand: 'TotalEnergies',
    category: 'Oils & Fluids',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 99,
    stock: 25,
    shopId: 'jenin-spare-parts',
    addedAt: '2026-09-05',
    fitments: [],
    universalFit: true,
  },
  {
    id: 'p-049',
    name: 'Automatic transmission fluid ATF, 1 L',
    oemNumber: '',
    manufacturerNumber: '152648',
    brand: 'Mobil',
    category: 'Oils & Fluids',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 42,
    stock: 30,
    shopId: 'hebron-genuine-parts',
    addedAt: '2026-08-28',
    fitments: [],
    universalFit: true,
  },
  {
    id: 'p-050',
    name: 'Coolant antifreeze G12, 5 L',
    oemNumber: '',
    manufacturerNumber: '37400',
    brand: 'Febi',
    category: 'Oils & Fluids',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 65,
    stock: 18,
    shopId: 'alquds-auto-parts',
    addedAt: '2026-09-12',
    fitments: [],
    universalFit: true,
  },
  {
    id: 'p-051',
    name: 'Brake fluid DOT 4, 1 L',
    oemNumber: '',
    manufacturerNumber: '1987479107',
    brand: 'Bosch',
    category: 'Oils & Fluids',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 35,
    stock: 50,
    shopId: 'alquds-auto-parts',
    addedAt: '2026-07-30',
    fitments: [],
    universalFit: true,
  },
  {
    id: 'p-052',
    name: 'Torque wrench, 40-210 Nm',
    oemNumber: '',
    manufacturerNumber: '6292-1CT',
    brand: 'Hazet',
    category: 'Tools',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 260,
    stock: 6,
    shopId: 'tulkarm-car-accessories',
    addedAt: '2026-09-18',
    fitments: [],
    universalFit: true,
  },
  {
    id: 'p-053',
    name: 'Socket set, 94 pieces',
    oemNumber: '',
    manufacturerNumber: 'S910',
    brand: 'Bahco',
    category: 'Tools',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 390,
    stock: 4,
    shopId: 'ramallah-motors-supply',
    addedAt: '2026-08-15',
    fitments: [],
    universalFit: true,
  },
  {
    id: 'p-054',
    name: 'Hydraulic floor jack, 2 t',
    oemNumber: '',
    manufacturerNumber: 'T82001',
    brand: 'Torin',
    category: 'Tools',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 450,
    stock: 3,
    shopId: 'tulkarm-car-accessories',
    addedAt: '2026-09-25',
    fitments: [],
    universalFit: true,
  },
  {
    id: 'p-055',
    name: 'OBD2 diagnostic scanner',
    oemNumber: '',
    manufacturerNumber: 'CR319',
    brand: 'Launch',
    category: 'Tools',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 220,
    stock: 9,
    shopId: 'jenin-spare-parts',
    addedAt: '2026-09-08',
    fitments: [],
    universalFit: true,
  },
  {
    id: 'p-056',
    name: 'Roof cross bars, aluminium',
    oemNumber: '',
    manufacturerNumber: '7106',
    brand: 'Thule',
    category: 'Accessories',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 520,
    stock: 5,
    shopId: 'tulkarm-car-accessories',
    addedAt: '2026-09-27',
    fitments: [fit('Volkswagen', 'Golf', 2013, 2020), fit('Hyundai', 'Accent', 2011, 2022)],
  },
  {
    id: 'p-057',
    name: 'Rear trunk lip spoiler, gloss black',
    oemNumber: '',
    manufacturerNumber: 'VW-GO-7-CAP1G',
    brand: 'Maxton',
    category: 'Accessories',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 280,
    stock: 7,
    shopId: 'tulkarm-car-accessories',
    addedAt: '2026-09-14',
    fitments: [fit('Volkswagen', 'Golf', 2013, 2020)],
  },
  {
    id: 'p-058',
    name: 'Dash camera, Full HD front',
    oemNumber: '',
    manufacturerNumber: 'A400',
    brand: '70mai',
    category: 'Accessories',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 230,
    stock: 11,
    shopId: 'ramallah-motors-supply',
    addedAt: '2026-09-29',
    fitments: [],
    universalFit: true,
  },
  {
    id: 'p-059',
    name: 'Magnetic phone holder, air vent',
    oemNumber: '',
    manufacturerNumber: 'SUGX-A01',
    brand: 'Baseus',
    category: 'Accessories',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 45,
    stock: 35,
    shopId: 'tulkarm-car-accessories',
    addedAt: '2026-08-20',
    fitments: [],
    universalFit: true,
  },
  {
    id: 'p-060',
    name: 'LED bulbs H7, pair',
    oemNumber: '',
    manufacturerNumber: '11972U2500CX',
    brand: 'Philips',
    category: 'Lighting',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 180,
    stock: 14,
    shopId: 'hebron-genuine-parts',
    addedAt: '2026-09-10',
    fitments: [fit('Volkswagen', 'Golf', 2004, 2020), fit('Hyundai', 'Accent', 2011, 2022), fit('Kia', 'Rio', 2012, 2021)],
  },
  {
    id: 'p-061',
    name: 'Side mirror, right, heated',
    oemNumber: '87620-1R010',
    manufacturerNumber: '8296808',
    brand: 'Van Wezel',
    category: 'Body',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 310,
    stock: 2,
    shopId: 'jenin-spare-parts',
    addedAt: '2026-09-03',
    fitments: [fit('Hyundai', 'Accent', 2011, 2017)],
  },
  {
    id: 'p-062',
    name: 'Winter tire 205/55 R16',
    oemNumber: '',
    manufacturerNumber: '574721',
    brand: 'Michelin',
    category: 'Tires & Wheels',
    type: 'aftermarket',
    condition: 'new',
    priceIls: 420,
    stock: 16,
    shopId: 'alquds-auto-parts',
    addedAt: '2026-09-16',
    fitments: VW_GROUP_MQB,
  },
]

// Admin-assigned tags (ids from features/admin/mockTags.js) and moderation state.
// Admins change both at /admin/tags and /admin/listings. t-3 is "On Offer": those parts make up the
// offer banners and the "On offer" row on /marketplace.
const SEED_PART_TAGS = {
  'p-001': ['t-2'],
  'p-004': ['t-3'],
  'p-037': ['t-2', 't-3'],
  'p-041': ['t-3'],
  'p-044': ['t-3'],
  'p-047': ['t-2', 't-3'],
  'p-050': ['t-3'],
  'p-052': ['t-3'],
  'p-055': ['t-3'],
  'p-056': ['t-3'],
  'p-060': ['t-3'],
  'p-062': ['t-3'],
}

// The price before the offer (shown struck through, with the discount). Only parts on offer have one.
const SEED_COMPARE_AT = {
  'p-004': 195,
  'p-037': 60,
  'p-041': 540,
  'p-044': 520,
  'p-047': 175,
  'p-050': 80,
  'p-052': 320,
  'p-055': 290,
  'p-056': 650,
  'p-060': 240,
  'p-062': 520,
}

// Units sold in the last 30 days, for "Most popular". TODO: real sales numbers from orders.
const SEED_SALES = {
  'p-001': 64,
  'p-004': 51,
  'p-005': 47,
  'p-009': 42,
  'p-017': 38,
  'p-047': 36,
  'p-023': 33,
  'p-042': 29,
  'p-045': 27,
  'p-014': 24,
  'p-037': 21,
  'p-051': 19,
  'p-028': 17,
  'p-012': 15,
  'p-059': 14,
  'p-044': 12,
}

// When the price or stock last changed, for "Recently updated". Shop edits and orders set it too.
const SEED_UPDATED = {
  'p-004': '2026-09-28',
  'p-007': '2026-09-21',
  'p-012': '2026-09-27',
  'p-020': '2026-09-29',
  'p-031': '2026-09-24',
  'p-041': '2026-09-26',
  'p-044': '2026-09-30',
}

for (const part of parts) {
  part.tagIds = SEED_PART_TAGS[part.id] ?? (part.type === 'oem' ? ['t-1'] : [])
  part.hidden = null
  part.compareAtPriceIls = SEED_COMPARE_AT[part.id] ?? null
  part.salesCount = SEED_SALES[part.id] ?? 0
  part.updatedAt = SEED_UPDATED[part.id] ?? part.addedAt
  part.universalFit = Boolean(part.universalFit)
}
