import { ROLES } from '../authorization/roles.js'
import {
  ACCOUNT_STATUS,
  DEFAULT_NOTIFICATION_PREFS,
  REVIEW_STATUS,
  ROLES_NEEDING_APPROVAL,
  SKILL_STATUS,
} from './constants.js'
import { avatarPhoto, logoImage, placePhoto, samplePdf, slug, truckPhoto } from './mockFiles.js'

// TODO: replace with real API call
// Accounts that exist when the app starts. Logins survive a page refresh (sessionStorage, see
// sessionPersistence.js); closing the tab resets everything.
//
// Test accounts (one per role - also listed in the root README and in the dev login panel):
//   admin@fastfix.test             Admin123!  admin
//   customer@fastfix.test          Test123!   customer
//   mechanic@fastfix.test          Test123!   mechanic, approved, 2 approved skills (Sami Odeh)
//   shop@fastfix.test              Test123!   parts shop "Al-Quds Auto Parts", owns its mock parts
//   shop2@fastfix.test             Test123!   parts shop "Ramallah Motors Supply", owns other parts
//   tow@fastfix.test               Test123!   tow company "Nablus Rescue Towing", 3 trucks (one
//                                             on an active tow request, one waiting for review)
//   pending-mechanic@fastfix.test  Test123!   mechanic, pending, 2 skills to review (Nour Daraghmeh)
// Every other seeded account also uses Test123!.
//
// Parts shop account ids are the same as the shop ids in features/marketplace/mockData.js,
// because a part belongs to the account whose id equals part.shopId.
// Two mechanics and one tow company are still "pending": they must not appear publicly.
// Items waiting in the admin's "Updates to review" queue: Nablus Rescue Towing's third truck and a
// name change from Ramallah Motors Supply. Sami Odeh (mechanic@) has a rejected Electrical skill
// with the admin's reason, to try re-submitting a certificate.

const PASSWORD = 'Test123!'
const { APPROVED, PENDING } = ACCOUNT_STATUS

function base({ id, role, status = APPROVED, name, email, phone, createdAt, tagIds = [] }) {
  const reviewed = status === APPROVED && ROLES_NEEDING_APPROVAL.includes(role)
  return {
    id,
    role,
    status,
    rejectionReason: null,
    createdAt,
    reviewedAt: reviewed ? createdAt : null,
    verification: reviewed ? { method: 'documents', note: 'Seed account', reviewedBy: 'u-1' } : null,
    suspended: false,
    suspendedAt: null,
    suspensionReason: null,
    tagIds,
    name,
    email,
    phone,
    password: PASSWORD,
    notificationPrefs: { ...DEFAULT_NOTIFICATION_PREFS },
    sessionsRevokedAt: null,
  }
}

// skills: [skill, years] or [skill, years, { status, rejectionReason, submittedAt }]
function mechanic({
  skills,
  color,
  workshopName,
  city,
  address,
  description = '',
  serviceModes = ['workshop'],
  onSiteCities = [],
  makes = [],
  base: basePoint = null,
  photoCaptions,
  ...account
}) {
  return {
    ...base({ ...account, role: ROLES.MECHANIC }),
    profilePhoto: avatarPhoto(account.name, color),
    city,
    workshopName,
    address,
    description,
    serviceModes,
    onSiteCities,
    makes,
    base: basePoint,
    skills: skills.map(([skill, years, review = {}], i) => ({
      id: `${account.id}-skill-${i + 1}`,
      skill,
      years,
      status: account.status === PENDING ? SKILL_STATUS.PENDING : SKILL_STATUS.APPROVED,
      rejectionReason: null,
      submittedAt: account.createdAt,
      ...review,
      certificate: samplePdf(`${slug(skill)}-certificate-${account.id}.pdf`, `${skill} certificate`, [
        `Awarded to: ${account.name}`,
        `Workshop: ${workshopName}, ${city}`,
        `Years of experience: ${years}`,
      ]),
    })),
    workshopPhotos: photoCaptions.map((caption, i) =>
      placePhoto(`${account.id}-workshop-${i + 1}.svg`, caption, color),
    ),
    pendingChanges: [],
  }
}

// trucks: [type, maxWeightKg, plateNumber, caption] plus an optional { status, reviewStatus, submittedAt }
// base: where the trucks are parked ({ lat, lng }, approximate). towServices: TOW_SERVICES values
// in features/logistics/constants.js.
function towCompany({ trucks, color, city, address, serviceArea, description, base: basePoint, towServices, ...account }) {
  return {
    ...base({ ...account, role: ROLES.TOW }),
    profilePhoto: logoImage(account.name, color),
    city,
    address,
    description,
    serviceArea,
    base: basePoint,
    towServices,
    businessLicense: samplePdf(`${account.id}-business-license.pdf`, 'Business license', [account.name, city]),
    trucks: trucks.map(([type, maxWeightKg, plateNumber, caption, extra = {}], i) => ({
      id: `${account.id}-truck-${i + 1}`,
      plateNumber,
      type,
      maxWeightKg,
      photos: [truckPhoto(`${account.id}-truck-${i + 1}.svg`, caption, color)],
      registration: samplePdf(`${account.id}-truck-${i + 1}-registration.pdf`, 'Vehicle registration', [plateNumber]),
      insurance: samplePdf(`${account.id}-truck-${i + 1}-insurance.pdf`, 'Insurance certificate', [plateNumber]),
      status: 'available',
      reviewStatus: account.status === PENDING ? REVIEW_STATUS.PENDING : REVIEW_STATUS.APPROVED,
      rejectionReason: null,
      submittedAt: account.createdAt,
      ...extra,
    })),
    pendingChanges: [],
  }
}

function partsShop({ color, city, address, description, pendingChanges = [], ...account }) {
  return {
    ...base({ ...account, role: ROLES.PARTS_SHOP }),
    profilePhoto: logoImage(account.name, color),
    city,
    address,
    description,
    businessLicense: samplePdf(`${account.id}-business-license.pdf`, 'Commercial registration', [account.name, city]),
    extraDocuments: [],
    shopPhotos: [placePhoto(`${account.id}-shop-1.svg`, `${account.name} storefront`, color)],
    pendingChanges,
  }
}

export const seedUsers = [
  {
    ...base({
      id: 'u-1',
      role: ROLES.ADMIN,
      name: 'FastFix Admin',
      email: 'admin@fastfix.test',
      phone: '',
      createdAt: '2026-09-01T08:00:00.000Z',
    }),
    password: 'Admin123!',
    profilePhoto: null,
  },
  {
    ...base({
      id: 'u-2',
      role: ROLES.CUSTOMER,
      name: 'Layla Customer',
      email: 'customer@fastfix.test',
      phone: '0599000001',
      createdAt: '2026-09-02T09:00:00.000Z',
    }),
    profilePhoto: null,
  },

  // --- Mechanics: 12 approved ---
  mechanic({
    id: 'u-10',
    name: 'Kareem Haddad',
    tagIds: ['t-4'],
    email: 'kareem@fastfix.test',
    phone: '0599100010',
    createdAt: '2026-09-03T08:00:00.000Z',
    workshopName: 'Kareem Auto Repair',
    city: 'Nablus',
    address: 'Industrial Area, Street 4',
    description: 'Engine and gearbox repairs for most makes. Diagnostics while you wait.',
    serviceModes: ['workshop', 'on_site'],
    onSiteCities: ['Nablus', 'Tulkarm'],
    skills: [
      ['Engine', 12],
      ['Computer Diagnostics', 8],
      ['Transmission', 10],
    ],
    base: { lat: 32.2301, lng: 35.2677 },
    makes: ['Volkswagen', 'Skoda', 'Audi', 'Mercedes-Benz'],
    photoCaptions: ['Kareem Auto Repair - main bay', 'Engine rebuild on a Golf'],
    color: '#1f6feb',
  }),
  mechanic({
    id: 'u-11',
    name: 'Omar Saleh',
    tagIds: ['t-5'],
    email: 'omar@fastfix.test',
    phone: '0599100011',
    createdAt: '2026-09-04T08:00:00.000Z',
    workshopName: 'FastLane Garage',
    city: 'Ramallah',
    address: 'Ring Road, near the stadium',
    description: "Brakes, suspension and tires for Japanese and Korean cars. Walk-ins welcome.",
    serviceModes: ['workshop', 'online'],
    skills: [
      ['Brakes', 6],
      ['Suspension', 7],
      ['Tires & Wheels', 5],
    ],
    base: { lat: 31.9121, lng: 35.2108 },
    makes: ['Toyota', 'Hyundai', 'Kia'],
    photoCaptions: ['FastLane Garage - front', 'Brake job on a Corolla'],
    color: '#1a7f37',
  }),
  mechanic({
    id: 'u-12',
    name: 'Yousef Khalil',
    email: 'yousef@fastfix.test',
    phone: '0599100012',
    createdAt: '2026-09-05T08:00:00.000Z',
    workshopName: 'Jenin Electric Auto',
    city: 'Jenin',
    address: 'Haifa Street 22',
    description: "Auto electricians: wiring faults, alternators, AC and diagnostics. We also come to you in Jenin.",
    serviceModes: ['workshop', 'on_site', 'online'],
    onSiteCities: ['Jenin'],
    skills: [
      ['Electrical', 9],
      ['AC & Cooling', 6],
      ['Computer Diagnostics', 4],
    ],
    base: { lat: 32.4655, lng: 35.2988 },
    makes: ['Kia', 'Hyundai', 'Peugeot'],
    photoCaptions: ['Diagnostics corner', 'Wiring repair on a Kia Rio'],
    color: '#8250df',
  }),
  mechanic({
    id: 'u-13',
    name: 'Mahmoud Jaber',
    email: 'mahmoud@fastfix.test',
    phone: '0599100013',
    createdAt: '2026-09-06T08:00:00.000Z',
    workshopName: 'Hebron Body & Paint',
    city: 'Hebron',
    address: 'Ein Sarah Street 7',
    description: "Dent repair, repainting and bumper work. Free estimate with photos.",
    skills: [['Body Work & Paint', 15]],
    base: { lat: 31.5309, lng: 35.0961 },
    makes: ['Hyundai', 'Toyota', 'Volkswagen', 'Ford'],
    photoCaptions: ['Paint booth', 'Bumper repair before painting', 'Finished Hyundai Elantra'],
    color: '#cf222e',
  }),
  mechanic({
    id: 'u-14',
    name: 'Lina Masri',
    tagIds: ['t-4', 't-6'],
    email: 'lina@fastfix.test',
    phone: '0599100014',
    createdAt: '2026-09-07T08:00:00.000Z',
    workshopName: 'Green Drive Hybrid Center',
    city: 'Bethlehem',
    address: 'Manger Street 90',
    description: "Hybrid and electric car service: battery checks, inverters and software updates.",
    serviceModes: ['workshop', 'online'],
    skills: [
      ['Hybrid/EV', 5],
      ['Electrical', 7],
      ['Computer Diagnostics', 6],
    ],
    base: { lat: 31.7088, lng: 35.2049 },
    makes: ['Toyota', 'Lexus', 'Hyundai', 'Kia'],
    photoCaptions: ['Hybrid battery bench', 'Prius inverter check'],
    color: '#0a7f7f',
  }),
  mechanic({
    id: 'u-15',
    name: 'Sami Odeh',
    email: 'mechanic@fastfix.test',
    phone: '0599100015',
    createdAt: '2026-09-08T08:00:00.000Z',
    workshopName: 'Tulkarm Transmission Works',
    city: 'Tulkarm',
    address: 'Nablus Street 15',
    description: 'Automatic and manual gearbox specialists. Clutch jobs in one day.',
    serviceModes: ['workshop', 'on_site'],
    onSiteCities: ['Tulkarm', 'Qalqilya'],
    skills: [
      ['Transmission', 14],
      ['Engine', 10],
      [
        'Electrical',
        3,
        {
          status: SKILL_STATUS.REJECTED,
          rejectionReason: 'This is a course attendance letter, not a trade certificate. Upload your electrical certificate.',
        },
      ],
    ],
    base: { lat: 32.3139, lng: 35.0331 },
    makes: ['Volkswagen', 'Mercedes-Benz', 'Toyota'],
    photoCaptions: ['Gearbox workbench', 'Clutch replacement on a Passat'],
    color: '#9a6700',
  }),
  mechanic({
    id: 'u-16',
    name: 'Ahmad Nasser',
    email: 'ahmad@fastfix.test',
    phone: '0599100016',
    createdAt: '2026-09-09T08:00:00.000Z',
    workshopName: 'Qalqilya Cool Air',
    city: 'Qalqilya',
    address: 'Main Street 3',
    description: "Mobile AC and cooling repair: recharge, leaks, radiators and fans. We come to your street.",
    serviceModes: ['on_site'],
    onSiteCities: ['Qalqilya', 'Tulkarm'],
    skills: [
      ['AC & Cooling', 11],
      ['Electrical', 5],
    ],
    base: { lat: 32.1912, lng: 34.9741 },
    makes: ['Kia', 'Hyundai', 'Toyota'],
    photoCaptions: ['AC recharge station', 'Radiator swap on a Sportage'],
    color: '#0969da',
  }),
  mechanic({
    id: 'u-17',
    name: 'Rami Awad',
    tagIds: ['t-6'],
    email: 'rami@fastfix.test',
    phone: '0599100017',
    createdAt: '2026-09-10T08:00:00.000Z',
    workshopName: 'Jericho Tire & Brake',
    city: 'Jericho',
    address: 'Ein Al-Sultan Street 11',
    description: "Tires, balancing, alignment and brake jobs while you wait. Open late.",
    skills: [
      ['Tires & Wheels', 8],
      ['Brakes', 9],
      ['Suspension', 4],
    ],
    base: { lat: 31.8641, lng: 35.4573 },
    makes: ['Toyota', 'Hyundai', 'Skoda', 'Kia'],
    photoCaptions: ['Tire fitting machine', 'Wheel alignment bay'],
    color: '#bc4c00',
  }),

  mechanic({
    id: 'u-41',
    name: 'Tariq Zidan',
    tagIds: ['t-6'],
    email: 'tariq.zidan@fastfix.test',
    phone: '0599100041',
    createdAt: '2026-09-11T08:00:00.000Z',
    workshopName: 'Ramallah Engine Clinic',
    city: 'Ramallah',
    address: 'Al-Masyoun, Street 12',
    description: 'Engine overhauls, timing belts and turbo repairs for European cars. Open around the clock for breakdowns.',
    serviceModes: ['workshop', 'on_site', 'online'],
    onSiteCities: ['Ramallah', 'Al-Bireh', 'Birzeit'],
    base: { lat: 31.9066, lng: 35.2011 },
    makes: ['Mercedes-Benz', 'BMW', 'Audi', 'Volkswagen'],
    skills: [
      ['Engine', 13],
      ['Computer Diagnostics', 9],
      ['Transmission', 6],
    ],
    photoCaptions: ['Engine clinic - main bay', 'Turbo rebuild on a Passat'],
    color: '#1f6feb',
  }),
  mechanic({
    id: 'u-42',
    name: 'Nour Hamdan',
    tagIds: ['t-4'],
    email: 'nour@fastfix.test',
    phone: '0599100042',
    createdAt: '2026-09-12T08:00:00.000Z',
    workshopName: 'Nablus Brakes & Suspension',
    city: 'Nablus',
    address: 'Rafidia Street 18',
    description: 'Brake, steering and suspension specialists. Same-day pad and disc replacement.',
    serviceModes: ['workshop', 'on_site'],
    onSiteCities: ['Nablus', 'Huwara'],
    base: { lat: 32.2279, lng: 35.2406 },
    makes: ['Toyota', 'Hyundai', 'Kia', 'Ford'],
    skills: [
      ['Brakes', 11],
      ['Suspension', 10],
      ['Tires & Wheels', 6],
    ],
    photoCaptions: ['Brake test bench', 'Suspension rebuild on a Tucson'],
    color: '#bf3989',
  }),
  mechanic({
    id: 'u-43',
    name: 'Fadi Abu Sneineh',
    tagIds: ['t-6'],
    email: 'fadi@fastfix.test',
    phone: '0599100043',
    createdAt: '2026-09-13T08:00:00.000Z',
    workshopName: 'Hebron Auto Electric & AC',
    city: 'Hebron',
    address: 'Wadi Al-Hariyeh 5',
    description: 'Electrical faults, car AC and diagnostics. Mobile service across Hebron.',
    serviceModes: ['workshop', 'on_site', 'online'],
    onSiteCities: ['Hebron', 'Halhul', 'Yatta'],
    base: { lat: 31.5362, lng: 35.1043 },
    makes: ['Hyundai', 'Kia', 'Toyota', 'Mitsubishi'],
    skills: [
      ['Electrical', 10],
      ['AC & Cooling', 8],
      ['Computer Diagnostics', 7],
    ],
    photoCaptions: ['Auto electric bench', 'AC leak test'],
    color: '#0a7f7f',
  }),
  mechanic({
    id: 'u-44',
    name: 'Huda Barghouti',
    email: 'huda@fastfix.test',
    phone: '0599100044',
    createdAt: '2026-09-14T08:00:00.000Z',
    workshopName: 'Birzeit Hybrid & EV Lab',
    city: 'Birzeit',
    address: 'University Road 3',
    description: 'Hybrid and electric car diagnostics, battery health reports and charging-port repair.',
    serviceModes: ['workshop', 'online'],
    base: { lat: 31.9722, lng: 35.1953 },
    makes: ['Tesla', 'Toyota', 'Hyundai', 'Kia'],
    skills: [
      ['Hybrid/EV', 7],
      ['Computer Diagnostics', 8],
      ['Electrical', 6],
    ],
    photoCaptions: ['EV diagnostics corner', 'Battery health check'],
    color: '#8250df',
  }),

  // --- Mechanics: 2 pending (hidden from the public directory) ---
  mechanic({
    id: 'u-18',
    status: PENDING,
    name: 'Tariq Hamdan',
    email: 'tariq@fastfix.test',
    phone: '0599100018',
    createdAt: '2026-09-25T08:00:00.000Z',
    workshopName: 'Salfit Motor Care',
    city: 'Salfit',
    address: 'Old Market Road 5',
    skills: [['Engine', 3]],
    photoCaptions: ['Salfit Motor Care - bay 1', 'Oil change on a Skoda Octavia'],
    color: '#57606a',
  }),
  mechanic({
    id: 'u-19',
    status: PENDING,
    name: 'Nour Daraghmeh',
    email: 'pending-mechanic@fastfix.test',
    phone: '0599100019',
    createdAt: '2026-09-26T08:00:00.000Z',
    workshopName: 'Tubas Auto Clinic',
    city: 'Tubas',
    address: 'Jenin Road 18',
    skills: [
      ['Brakes', 2],
      ['Electrical', 2],
    ],
    photoCaptions: ['Tubas Auto Clinic - entrance', 'Brake pad check'],
    color: '#57606a',
  }),

  // --- Tow companies: 4 approved ---
  towCompany({
    id: 'u-30',
    name: 'Nablus Rescue Towing',
    tagIds: ['t-7', 't-8'],
    email: 'tow@fastfix.test',
    phone: '0599200030',
    createdAt: '2026-09-03T10:00:00.000Z',
    city: 'Nablus',
    address: 'Faisal Street 40',
    description: '24/7 towing across the northern West Bank. Flatbed transport for low cars.',
    serviceArea: ['Nablus', 'Tulkarm', 'Jenin', 'Qalqilya'],
    base: { lat: 32.2227, lng: 35.2621 },
    towServices: ['local', 'roadside', 'accident_recovery', 'intercity'],
    trucks: [
      // On the active tow request r-4 (features/requests/mockRequests.js), so it can't be removed
      ['flatbed', 3500, '7-4512-93', 'Flatbed ready for pickup', { status: 'en_route' }],
      ['wheel_lift', 2500, '7-4513-93', 'Wheel-lift truck'],
      [
        'flatbed',
        4500,
        '7-4514-93',
        'New long flatbed',
        { status: 'out_of_service', reviewStatus: REVIEW_STATUS.PENDING, submittedAt: '2026-09-29T09:00:00.000Z' },
      ],
    ],
    color: '#cf222e',
  }),
  towCompany({
    id: 'u-31',
    name: 'Al-Bireh Road Assist',
    tagIds: ['t-9', 't-7'],
    email: 'albireh-assist@fastfix.test',
    phone: '0599200031',
    createdAt: '2026-09-04T10:00:00.000Z',
    city: 'Ramallah',
    address: 'Al-Bireh, Jerusalem Street 12',
    description: 'Car and van towing, plus heavy recovery for trucks and buses.',
    serviceArea: ['Ramallah', 'Al-Bireh', 'Jericho'],
    base: { lat: 31.9112, lng: 35.2178 },
    towServices: ['local', 'heavy_duty', 'accident_recovery', 'intercity'],
    trucks: [
      ['flatbed', 4000, '6-2201-91', 'Flatbed with winch'],
      ['flatbed', 8000, '6-2202-91', 'Long flatbed for vans'],
      ['other', 18000, '6-2203-91', 'Heavy recovery truck'],
    ],
    color: '#1f6feb',
  }),
  towCompany({
    id: 'u-32',
    name: 'South Star Towing',
    tagIds: ['t-8'],
    email: 'south-star@fastfix.test',
    phone: '0599200032',
    createdAt: '2026-09-05T10:00:00.000Z',
    city: 'Hebron',
    address: 'Wadi Al-Tuffah 3',
    description: 'Fast local towing in the south. Fixed prices inside Hebron.',
    serviceArea: ['Hebron', 'Bethlehem'],
    base: { lat: 31.5401, lng: 35.0912 },
    towServices: ['local', 'roadside'],
    trucks: [['flatbed', 3500, '9-7781-95', 'South Star flatbed']],
    color: '#9a6700',
  }),
  towCompany({
    id: 'u-33',
    name: 'Jenin Valley Tow',
    email: 'jenin-valley@fastfix.test',
    phone: '0599200033',
    createdAt: '2026-09-06T10:00:00.000Z',
    city: 'Jenin',
    address: 'Nazareth Street 9',
    description: 'Family-run towing company serving Jenin, Tubas and Nablus since 2008.',
    serviceArea: ['Jenin', 'Tubas', 'Nablus'],
    base: { lat: 32.4589, lng: 35.2952 },
    towServices: ['local', 'accident_recovery'],
    trucks: [
      ['wheel_lift', 2000, '8-3390-94', 'Compact wheel-lift'],
      ['flatbed', 3000, '8-3391-94', 'Flatbed for accident cars'],
    ],
    color: '#1a7f37',
  }),

  // More approved tow companies, spread across the West Bank so the city search and the
  // distance sorting on /tow-companies can be tried. (They stay out of Jenin and have no "Heavy
  // Vehicles" tag: the api's search tests expect the companies above for those.)
  towCompany({
    id: 'u-35',
    name: 'Qalqilya Express Towing',
    tagIds: ['t-8'],
    email: 'qalqilya-express@fastfix.test',
    phone: '0599200035',
    createdAt: '2026-09-08T10:00:00.000Z',
    city: 'Qalqilya',
    address: 'Nablus Street 61',
    description: 'Quick towing and roadside help around Qalqilya, Azzun and Tulkarm.',
    serviceArea: ['Qalqilya', 'Azzun', 'Tulkarm', 'Salfit'],
    base: { lat: 32.1902, lng: 34.9758 },
    towServices: ['local', 'roadside', 'accident_recovery'],
    trucks: [
      ['wheel_lift', 2500, '5-1201-92', 'Qalqilya Express wheel-lift'],
      ['flatbed', 3500, '5-1202-92', 'Qalqilya Express flatbed'],
    ],
    color: '#bf3989',
  }),
  towCompany({
    id: 'u-36',
    name: 'Bethlehem Highway Recovery',
    tagIds: ['t-7'],
    email: 'bethlehem-highway@fastfix.test',
    phone: '0599200036',
    createdAt: '2026-09-09T10:00:00.000Z',
    city: 'Bethlehem',
    address: 'Hebron Road 120',
    description: 'Around the clock accident recovery and transport between the southern cities.',
    serviceArea: ['Bethlehem', 'Beit Sahour', 'Beit Jala', 'Halhul', 'Hebron'],
    base: { lat: 31.6952, lng: 35.1968 },
    towServices: ['local', 'accident_recovery', 'intercity', 'roadside'],
    trucks: [
      ['flatbed', 4000, '4-2310-97', 'Bethlehem Highway flatbed'],
      ['flatbed', 4000, '4-2311-97', 'Second flatbed', { status: 'busy' }],
      ['wheel_lift', 2500, '4-2312-97', 'City wheel-lift'],
    ],
    color: '#0a7f7f',
  }),
  towCompany({
    id: 'u-37',
    name: 'Jericho Valley Assist',
    email: 'jericho-valley@fastfix.test',
    phone: '0599200037',
    createdAt: '2026-09-10T10:00:00.000Z',
    city: 'Jericho',
    address: 'Ein Al-Sultan Street 8',
    description: 'Roadside assistance in the Jordan Valley, and towing up to Ramallah.',
    serviceArea: ['Jericho', 'Ramallah', 'Al-Bireh'],
    base: { lat: 31.8667, lng: 35.4489 },
    towServices: ['roadside', 'local', 'intercity'],
    trucks: [['flatbed', 3500, '3-5520-96', 'Valley flatbed']],
    color: '#bc4c00',
  }),
  towCompany({
    id: 'u-38',
    name: 'Ramallah City Tow',
    tagIds: ['t-7', 't-8'],
    email: 'ramallah-city@fastfix.test',
    phone: '0599200038',
    createdAt: '2026-09-11T10:00:00.000Z',
    city: 'Ramallah',
    address: 'Al-Irsal Street 30',
    description: '24/7 city towing in Ramallah, Al-Bireh and Birzeit. Most calls answered within 20 minutes.',
    serviceArea: ['Ramallah', 'Al-Bireh', 'Birzeit'],
    base: { lat: 31.8995, lng: 35.2058 },
    towServices: ['local', 'roadside'],
    trucks: [
      ['wheel_lift', 2500, '6-4410-91', 'City wheel-lift'],
      ['flatbed', 3500, '6-4411-91', 'City flatbed'],
      ['flatbed', 3500, '6-4412-91', 'Second city flatbed'],
      ['wheel_lift', 2000, '6-4413-91', 'Small wheel-lift', { status: 'out_of_service' }],
    ],
    color: '#8250df',
  }),
  towCompany({
    id: 'u-39',
    name: 'Tubas Rural Recovery',
    email: 'tubas-rural@fastfix.test',
    phone: '0599200039',
    createdAt: '2026-09-12T10:00:00.000Z',
    city: 'Tubas',
    address: 'Main Road 4',
    description: 'Towing and recovery for farm roads and heavy vehicles around Tubas and Tammun.',
    serviceArea: ['Tubas', 'Tammun', 'Nablus'],
    base: { lat: 32.3218, lng: 35.3655 },
    towServices: ['local', 'heavy_duty', 'accident_recovery'],
    trucks: [
      ['other', 12000, '8-7710-94', 'Recovery truck for heavy vehicles'],
      ['flatbed', 3500, '8-7711-94', 'Tubas flatbed'],
    ],
    color: '#1a7f37',
  }),
  towCompany({
    id: 'u-40',
    name: 'Salfit Mountain Tow',
    tagIds: ['t-8'],
    email: 'salfit-mountain@fastfix.test',
    phone: '0599200040',
    createdAt: '2026-09-13T10:00:00.000Z',
    city: 'Salfit',
    address: 'Municipality Square 2',
    description: 'Local towing in Salfit and the nearby villages, and transport to Nablus and Ramallah.',
    serviceArea: ['Salfit', 'Huwara', 'Nablus', 'Ramallah'],
    base: { lat: 32.0849, lng: 35.1822 },
    towServices: ['local', 'intercity'],
    trucks: [['wheel_lift', 2500, '7-6601-93', 'Salfit wheel-lift', { status: 'busy' }]],
    color: '#57606a',
  }),
  towCompany({
    id: 'u-45',
    name: 'Rafidia Road Assist',
    tagIds: ['t-7'],
    email: 'rafidia-assist@fastfix.test',
    phone: '0599200045',
    createdAt: '2026-09-15T10:00:00.000Z',
    city: 'Nablus',
    address: 'Rafidia Street 60',
    description: 'Fast towing and roadside help inside Nablus. Usually there in 15 minutes.',
    serviceArea: ['Nablus', 'Huwara', 'Tubas'],
    base: { lat: 32.2282, lng: 35.2347 },
    towServices: ['local', 'roadside', 'accident_recovery'],
    trucks: [
      ['wheel_lift', 2500, '7-8801-93', 'Rafidia wheel-lift'],
      ['flatbed', 3500, '7-8802-93', 'Rafidia flatbed'],
    ],
    color: '#bf3989',
  }),
  towCompany({
    id: 'u-46',
    name: 'Balata Quick Tow',
    email: 'balata-tow@fastfix.test',
    phone: '0599200046',
    createdAt: '2026-09-16T10:00:00.000Z',
    city: 'Nablus',
    address: 'East Nablus, Balata Road 3',
    description: 'Local towing east of Nablus, day and night.',
    serviceArea: ['Nablus', 'Tammun', 'Tubas'],
    base: { lat: 32.2139, lng: 35.2886 },
    towServices: ['local', 'roadside'],
    trucks: [['flatbed', 3500, '7-8810-93', 'Balata flatbed']],
    color: '#0969da',
  }),

  // --- Tow companies: 1 pending (hidden from the public directory) ---
  towCompany({
    id: 'u-34',
    status: PENDING,
    name: 'Bethlehem Quick Tow',
    email: 'bethlehem-quick@fastfix.test',
    phone: '0599200034',
    createdAt: '2026-09-27T10:00:00.000Z',
    city: 'Bethlehem',
    address: 'Hebron Road 55',
    description: 'New towing service in Bethlehem and Beit Sahour.',
    serviceArea: ['Bethlehem', 'Beit Sahour'],
    base: { lat: 31.7031, lng: 35.2055 },
    towServices: ['local'],
    trucks: [['flatbed', 3500, '4-1188-97', 'Quick Tow flatbed']],
    color: '#57606a',
  }),

  // --- Parts shops (ids match the shops in features/marketplace/mockData.js) ---
  partsShop({
    id: 'alquds-auto-parts',
    name: 'Al-Quds Auto Parts',
    email: 'shop@fastfix.test',
    phone: '0599300001',
    createdAt: '2026-09-02T12:00:00.000Z',
    city: 'Nablus',
    address: 'Sufian Street 20',
    description: 'Brakes, filters and electrical parts for European and Korean cars. Same-day pickup in Nablus.',
    color: '#1f6feb',
  }),
  partsShop({
    id: 'ramallah-motors-supply',
    name: 'Ramallah Motors Supply',
    email: 'shop2@fastfix.test',
    phone: '0599300002',
    createdAt: '2026-09-02T12:30:00.000Z',
    city: 'Ramallah',
    address: 'Irsal Street 8',
    description: 'Aftermarket parts from Bosch, Brembo and Gates, plus clutch and transmission kits.',
    pendingChanges: [
      {
        field: 'name',
        value: 'Ramallah Motors & Supply',
        status: REVIEW_STATUS.PENDING,
        submittedAt: '2026-09-28T11:00:00.000Z',
        rejectionReason: null,
      },
    ],
    color: '#1a7f37',
  }),
  partsShop({
    id: 'jenin-spare-parts',
    name: 'Jenin Spare Parts Center',
    email: 'jenin-parts@fastfix.test',
    phone: '0599300003',
    createdAt: '2026-09-02T13:00:00.000Z',
    city: 'Jenin',
    address: 'Abu Bakr Street 31',
    description: 'New and used parts, including tested used body parts and refurbished alternators.',
    color: '#8250df',
  }),
  partsShop({
    id: 'tulkarm-car-accessories',
    name: 'Tulkarm Car Accessories',
    email: 'tulkarm-accessories@fastfix.test',
    phone: '0599300004',
    createdAt: '2026-09-02T13:30:00.000Z',
    city: 'Tulkarm',
    address: 'Nablus Street 60',
    description: 'Lighting, accessories and cooling parts. Headlight fitting available on request.',
    color: '#bc4c00',
  }),
  partsShop({
    id: 'hebron-genuine-parts',
    name: 'Hebron Genuine Parts',
    email: 'hebron-genuine@fastfix.test',
    phone: '0599300005',
    createdAt: '2026-09-02T14:00:00.000Z',
    city: 'Hebron',
    address: 'King Faisal Street 14',
    description: 'Genuine OEM parts for VW, Toyota, Hyundai, Kia and Mercedes-Benz.',
    color: '#cf222e',
  }),
]
